per_listener_settings true

listener 1883
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl

listener 9999
protocol websockets
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl
cafile /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/server.crt
keyfile /mosquitto/config/certs/server.key
tls_version tlsv1.2

persistence true
persistence_location /mosquitto/data/
autosave_interval 60

max_queued_messages 1000
queue_qos0_messages true

log_dest stdout
log_timestamp true
connection_messages true
log_type error
log_type warning
log_type notice
log_type information
log_type subscribe
log_type unsubscribe

connection uni-bridge
address pcfeib425t.vsb.cz:1883
clientid mschat-bridge-fiu0013
remote_username server
remote_password Broker
bridge_protocol_version mqttv311
bridge_attempt_unsubscribe false
cleansession false
try_private true
start_type automatic
topic /mschat/# both 1
