services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: chatms-mosquitto
    ports:
      - "1883:1883"
      - "9999:9999"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    restart: unless-stopped
